defaults_rm:
  rng_seed: 0xa1221f97
  is_reward_model: true
  pooling: last
  learning_rate: 1e-5
  gradient_checkpointing: false
  gradient_accumulation_steps: 2
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 2
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_epsilon: 1e-12
  weight_decay: 0.00
  warmup_steps: 10
  eval_steps: 50
  save_steps: 100
  save_strategy: steps
  max_length: 512
  num_train_epochs: 10
  logging_steps: 10
  max_grad_norm: 2.0
  save_total_limit: 4
  dtype: fp16
  eval_accumulation_steps:
  freeze_layer:
  cache_dir: .cache
  loss_fn: RMLoss
  score_l2_reg: 0.001
  eval_size:
  log_dir: "base"
  quantization: true
  seq2seqmodel: false
  fuse_gelu: true
  log_wandb: true
  verbose: false
  output_dir: .saved_models_rm
  use_custom_sampler: false
  residual_dropout: 0.0
  residual_dropout_lima: false
  use_flash_attention: false
  sort_by_length: false
  per_digit_tokens: false
  datasets_extra: []
  metrics: ["accuracy", "kendalltau"]
  deepspeed_config: configs/zero_config.json
  max_replies: 5

oasst-rm-1-pythia-1.4b:
  is_reward_model: true
  pooling: last
  datasets:
    - oasst_export:
        lang: "en,es,de,fr"
        hf_dataset_name: OpenAssistant/oasst1
        val_split: 0.1
  w_datasets:
    - anthropic_rlhf_helpful:
        fraction: 0.1
        max_val_set: 1000
    - anthropic_rlhf_harmless:
        fraction: 0.1
        max_val_set: 1000
  use_custom_sampler: true
  sort_by_length: false
  model_name: andreaskoepf/pythia-1.4b-gpt4all-pretrain
  learning_rate: 8e-6
  residual_dropout: 0.01
  weight_decay: 0.0
  dtype: float32
  max_length: 2048
  use_flash_attention: true
  warmup_steps: 500
  gradient_accumulation_steps: 4
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 5
  num_train_epochs: 10
  eval_steps: 500
  save_steps: 1000


helpful-only:
  is_reward_model: true
  pooling: last
  datasets:
    - anthropic_rlhf_helpful:
        fraction: 0.1
        max_val_set: 1000
  w_datasets:
  use_custom_sampler: true
  sort_by_length: false
  model_name: andreaskoepf/pythia-1.4b-gpt4all-pretrain
  learning_rate: 8e-6
  residual_dropout: 0.01
  weight_decay: 0.0
  dtype: float32
  max_length: 2048
  use_flash_attention: false
  warmup_steps: 50
  gradient_accumulation_steps: 2
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 5
  num_train_epochs: 100
  eval_steps: 500
  save_steps: 1000
  log_dir: "helpful-only"


harmless-only:
  is_reward_model: true
  pooling: last
  datasets:
    - anthropic_rlhf_harmless:
        fraction: 0.1
        max_val_set: 1000
  w_datasets:
  use_custom_sampler: true
  sort_by_length: false
  model_name: andreaskoepf/pythia-1.4b-gpt4all-pretrain
  learning_rate: 8e-6
  residual_dropout: 0.01
  weight_decay: 0.0
  dtype: float32
  max_length: 2048
  use_flash_attention: false
  warmup_steps: 50
  gradient_accumulation_steps: 2
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 5
  num_train_epochs: 100
  eval_steps: 500
  save_steps: 1000
  log_dir: "harmless-only"

hh-data:
  is_reward_model: true
  pooling: last
  datasets:
    - anthropic_rlhf_helpful:
        fraction: 0.1
        max_val_set: 1000
    - anthropic_rlhf_harmless:
        fraction: 0.1
        max_val_set: 1000
  w_datasets:
  use_custom_sampler: true
  sort_by_length: false
  model_name: andreaskoepf/pythia-1.4b-gpt4all-pretrain
  learning_rate: 8e-6
  residual_dropout: 0.01
  weight_decay: 0.0
  dtype: float32
  max_length: 2048
  use_flash_attention: false
  warmup_steps: 50
  gradient_accumulation_steps: 2
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 5
  num_train_epochs: 10
  eval_steps: 500
  save_steps: 1000
  log_dir: "hh-data"